apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: web-client-port
  type: ClusterIP
  selector:
    app: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: web
  labels:
    app: web
spec:
  progressDeadlineSeconds: 30
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: tbrock/simple-pg:latest
        imagePullPolicy: Always
        name: web
        command: ["yarn", "start-pg"]
        env:
        - name: PG_URI
          value: 'postgres://simple:password@postgres:5432'
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
